server:
  port: 9090
datasource:
  driverName: mysql
  port: 3306
  host: localhost
  database: rankwill
  username: root
  password: 123456
  charset: utf8mb4
redisconfig:
  address: localhost:6379
  password: